apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookinfo-b
  namespace: bookinfo
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: bookinfo
    server: {{ .Values.spec.destination.server }}
  project: bookinfo
  source:
    chart: https://github.com/thiagonache/bookinfo
    targetRevision: HEAD
